양 끝에 아이콘을 추가할 수 있는 Edit Text & 검증 텍스트와 텍스트 제한 기능이 있는 Edit Text 구현
GO-GO-NEVER-END/Royal-Flush-Android pull request #12
Opened 2023-05-16 15:45 UTC by soopeach

resolved: #9 

## 작업 내용

- 양 끝에 아이콘을 추가할 수 있는 Edit Text 구현 (RoyaFlushIconEditText)
- 텍스트 검증, 글자 수 제한 + 글자 수 세기 기능이 있는 Edit Text 구현 (RoyalFlushVerificationEditText)

## 사용 방법

### RoyaFlushIconEditText

<img width="511" alt="Screenshot 2023-05-17 at 12 29 14 AM" src="https://github.com/GO-GO-NEVER-END/Royal-Flush-Android/assets/90144041/ce8573ef-2bfb-4c0c-890b-2f0b40aa174c">

- `royalFlushIconEditTextHint` 속성으로 힌트 지정 가능. 
- `startIcon` 속성으로 시작 쪽 아이콘 지정 가능. 
- `endIcon` 속성으로 끝 쪽 아이콘 지정 가능. 

<img width="426" alt="Screenshot 2023-05-17 at 12 32 44 AM" src="https://github.com/GO-GO-NEVER-END/Royal-Flush-Android/assets/90144041/73391989-52c9-4a4f-9f0b-40586f9346b7">

### RoyalFlushVerificationEditText

<img width="587" alt="Screenshot 2023-05-17 at 12 34 30 AM" src="https://github.com/GO-GO-NEVER-END/Royal-Flush-Android/assets/90144041/09b48291-facf-4374-b1e0-8bb0a20a1081">

- `royalFlushVerificationEditTextHint` 속성으로 힌트 지정 가능. 
- `isCounterVisible` 속성으로 텍스트 카운터 텍스트 visibility 여부 지정 가능.
- `isVerificationVisible` 속성으로 초기 검증 텍스트 visibility 지정 가능.
- `verificationText` 속성으로 초기 검증 텍스트 지정 가능.
- `maxLength`최대 글자 수 제한 가능.

<img width="413" alt="Screenshot 2023-05-17 at 12 37 28 AM" src="https://github.com/GO-GO-NEVER-END/Royal-Flush-Android/assets/90144041/69e52cfa-0868-4171-9a2d-dd60bf12cda2">

### RoyalFlushVerificationEditText 추가 기능

<img width="597" alt="Screenshot 2023-05-17 at 12 41 25 AM" src="https://github.com/GO-GO-NEVER-END/Royal-Flush-Android/assets/90144041/48b73abd-08cf-49d7-b355-1e77556de66a">

- setVerificationText() 메서드로 검증 텍스트 변경 가능

<img width="570" alt="Screenshot 2023-05-17 at 12 42 27 AM" src="https://github.com/GO-GO-NEVER-END/Royal-Flush-Android/assets/90144041/2393842a-b45a-4135-b4b1-310d00b6d16a">

- addAfterTextChangedListener 확장함수와 setVerification() 메서드를 조합해서 실시간으로 검증 여부 설정 및 판단 가능

2023-05-18 01:40 UTC, swjw13 approved these changes
고생많으셨습니다!!
추후에 정리할때 만드신 뷰의 다양한 케이스를 보여주면 좋을거같아요(iconedittext에서icon을 각각 안넣었을때 어떻게 된다던가, verticaledittext애서 글자 수를 넘을때는 어떻게 되는가 등등....)
물론 현수님아 테스트 다 했을테지만..ㅎㅎㅎ

2023-05-18 03:27 UTC, soopeach commented
>  verticaledittext애서 글자 수를 넘을때는 어떻개되는가 등등....)   

검증된 텍스트의 길이가 엄청 길어지게 될 거라고는 생각을 못했어요..!! 고려(호랑이)해봐야겠습니다.
커스텀 뷰 위키에 사용법 올려두면 좋을 것 같아서 추후에 조금 더 상세하게 정리해놓을게용!!

2023-05-18 12:11 UTC, bngsh approved these changes, later dismissed
감사합니당 잘 쓰겠습니다!

2023-05-22 07:43 UTC, ldh019 requested changes
컨벤션 수정만 해주시면 될거같슴다

2023-05-22 07:43 UTC, ldh019 commented on feature/feature-common/src/main/res/drawable/royal_flush_edit_text_background.xml
> +            <solid android:color="#DFDBCC" />
이런 리소스에 있는 hex color도 테마에 미리 정해놓은걸로 쓸수있나요?

2023-05-22 07:43 UTC, ldh019 commented on feature/feature-common/src/main/res/layout/royal_flush_verification_edit_text.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
ConstraintLayout이 중첩으로 쓰인 이유가 있을까요?

2023-05-22 07:43 UTC, ldh019 commented on feature/feature-common/src/main/res/layout/royal_flush_icon_edit_text.xml
> +        android:id="@+id/start_ic"
어라라 컨벤션이

2023-05-22 07:45 UTC, soopeach commented on feature/feature-common/src/main/res/drawable/royal_flush_edit_text_background.xml
> +            <solid android:color="#DFDBCC" />
그럼요

2023-05-22 07:46 UTC, soopeach commented on feature/feature-common/src/main/res/layout/royal_flush_verification_edit_text.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Linear로 개선이 가능해보이네요 감사합니다!

2023-05-22 07:47 UTC, soopeach commented on feature/feature-common/src/main/res/layout/royal_flush_icon_edit_text.xml
> +        android:id="@+id/start_ic"
아 맞다

2023-05-22 13:08 UTC, jeeminimini submitted a review, later dismissed
아이콘 넣을 수 있는거 이쁘네용

2023-05-24 03:37 UTC, swjw13 submitted a review, later dismissed
이뻐이뻐

2024-03-18 08:47 UTC, ldh019 commented on feature/feature-common/src/main/res/layout/royal_flush_icon_edit_text.xml
> +        android:id="@+id/start_ic"
@soopeach 이거 해줘

2024-03-26 13:22 UTC, ldh019 approved these changes
LGTM!

2024-03-26 13:23 UTC, merged