feature/navigation : 멀티모듈 내비게이션 설정
GO-GO-NEVER-END/Royal-Flush-Android pull request #6
Opened 2023-05-01 09:02 UTC by yangsooplus

## 작업 내용
- 내비게이션 설정
- feature-map ➡ feature-home, feature-more ➡ feature-mypage 모듈 이름 변경

## 동작 화면

![rth](https://user-images.githubusercontent.com/69582122/235431742-65d0cb2f-fc33-42db-bb2a-8faf12c40bd9.gif)

## 메모
- 모듈 이름을 refactor로 변경 후에도 debug와 같이 자동으로 생성되는 파일들에는 반영되지 않았음. 강제로 보이는 모든 이름을 바꾸어보아도 계속 원래 이름으로 재생성됨.
    - 아예 home, mypage 모듈을 삭제하고 새로 만들어서 설정.
- Duplicate Implementation은 `androidx-navigation-safeargs`의 문제로 생각됨. 
    - 일단 제외시킴, 필요할 때 세팅을 다른 방법으로 해야할듯한...
    -  build-logic 말고 일반 설정때에도 `androidx-navigation-safeargs`를 적는 위치가 다르던데.. 이거때문인가?

2023-05-01 15:20 UTC, ldh019 commented on app/build.gradle.kts
> +    // implementation(libs.androidx.fragment.ktx)
이거 이제 다시 추가해야 하는거 아닌가요? 안해도 잘 되나요?

2023-05-01 15:22 UTC, ldh019 commented on feature/feature-home/proguard-rules.pro
> +# proguardFiles setting in build.gradle.
주석..이긴한데 kts가 붙어있어야 하는거 아닌가?

2023-05-01 15:22 UTC, ldh019 commented on feature/feature-home/src/androidTest/java/com/ggne/feature_home/ExampleInstrumentedTest.kt
> +        assertEquals("com.ggne.feature_home.test", appContext.packageName)
얘는 왜 어쩌다가 more(현 mypage)가 home(구 map)으로 바뀐거지..? 뭔가 이상한데

2023-05-01 15:25 UTC, ldh019 commented on feature/feature-home/build.gradle.kts
> +    id("org.jetbrains.kotlin.android")
얘는... 쌩으로 plugin을 적어놨네

2023-05-01 15:25 UTC, ldh019 commented on feature/feature-subway/build.gradle.kts
> +    alias(libs.plugins.kotlin.android)
얘는 또 alias 를 쓰고 있고..

2023-05-01 15:26 UTC, ldh019 commented on gradle/libs.versions.toml
> +navigation = ["androidx-navigation-fragment-ktx", "androidx-navigation-ui-ktx"]
그래서 우리의 safe args는 어떻게 써야하죠

2023-05-01 15:26 UTC, ldh019 commented on gradle/libs.versions.toml
>  android-base = ["androidx-livedata-ktx"]
하는김에 이 android-base 를 다 없애주세요

2023-05-01 15:27 UTC, ldh019 commented on settings.gradle.kts
> +include(":feature:feature-mypage")
위치도 저쪼아래로 내려주세용

2023-05-01 15:27 UTC, ldh019 requested changes
중복되는 것들은 코멘트를 안남겼어요 한번 전체적으로 확인해야할듯?

2023-05-02 05:12 UTC, yangsooplus commented on app/build.gradle.kts
> +    // implementation(libs.androidx.fragment.ktx)
이거 한번 빼봤는데 되더라고요? 혹시 몰라서 주석처리 해놨는데, 정상 실행되는걸 보면,, 이친구가 문제가 아니었던거 같아요

2023-05-02 05:21 UTC, soopeach commented on feature/feature-home/src/androidTest/java/com/ggne/feature_home/ExampleInstrumentedTest.kt
> +        assertEquals("com.ggne.feature_home.test", appContext.packageName)
모듈이 아주 꼬였구나

2023-05-02 05:29 UTC, yangsooplus commented on settings.gradle.kts
> +include(":feature:feature-mypage")
롸져

2023-05-02 05:29 UTC, yangsooplus commented on feature/feature-home/proguard-rules.pro
> +# proguardFiles setting in build.gradle.
붙여드렸습니다

2023-05-02 05:29 UTC, yangsooplus commented on feature/feature-home/build.gradle.kts
> +    id("org.jetbrains.kotlin.android")
alias로 통일했소

2023-05-02 05:29 UTC, yangsooplus commented on gradle/libs.versions.toml
>  android-base = ["androidx-livedata-ktx"]
넵~ android-data-base는 데이터 모듈 구성할 때 사용할 것 같아서 android-base만 지웠습니다

2023-05-02 05:34 UTC, soopeach reviewed
고생 많으셨어요 수진님..!

2023-05-02 05:34 UTC, soopeach commented on app/build.gradle.kts
> +    // implementation(libs.androidx.fragment.ktx)
옹 잘된다면 아예 지워버려도 좋을 것 같아용

2023-05-02 05:34 UTC, soopeach commented on app/src/main/java/com/ggne/royalflush/MainActivity.kt
> +    }
동작 모습 보니까 home_fragment만 root로 인식하는 것 같아서 나중에 요쪽 손봐야할 것 같아요

2023-05-02 05:34 UTC, soopeach commented on app/src/main/res/layout/activity_main.xml
> +       tools:layout_editor_absoluteY="0dp" />
요거 두 개 필요없어보이네요??

2023-05-02 05:34 UTC, soopeach commented on gradle/libs.versions.toml
> +navigation = ["androidx-navigation-fragment-ktx", "androidx-navigation-ui-ktx"]
그러게요....

2023-05-03 06:49 UTC, ldh019 commented on build-logic/convention/src/main/kotlin/AndroidHiltConventionPlugin.kt
> +                apply("kotlin-kapt")
어디선가 봤는데 kapt는 항상 마지막에 하래요. 안하면 build warnings이 뜬다나 뭐라나

2023-05-03 06:53 UTC, ldh019 submitted a review, later dismissed
LGTM ~

2023-05-03 07:06 UTC, bngsh submitted a review, later dismissed
고생하셨습니다 "The Genius"

2023-05-03 07:09 UTC, swjw13 submitted a review, later dismissed
destination 설정 바꿔서 뒤로가기만 없애면 좋을거같아요..고생하셧습니다!!!

2023-05-04 14:41 UTC, jeeminimini approved these changes, later dismissed
갓수진님 고생하셨습니다~ 👍

2023-05-06 23:49 UTC, ldh019 approved these changes

2023-05-07 01:30 UTC, soopeach approved these changes

2023-05-07 01:30 UTC, soopeach commented on app/src/main/java/com/ggne/royalflush/MainActivity.kt
> +                com.ggne.feature_mypage.R.id.fragment_mypage
import 안하고 앞에 패키지 명을 붙여서 사용하신 이유가 있나요???

2023-05-07 05:26 UTC, swjw13 approved these changes
주말은 쉬는날입니다 여러분...고생하셨습니다!!

2023-05-07 08:44 UTC, jeeminimini approved these changes

2023-05-07 09:21 UTC, merged

2023-05-07 10:39 UTC, ldh019 commented on app/src/main/java/com/ggne/royalflush/MainActivity.kt
> +                com.ggne.feature_mypage.R.id.fragment_mypage
근데 뭐 어차피 저 모듈에 저거 밖에 없으니까 뭐 그냥 냅둬도 뭐 그냥 뭐..